services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
      POSTGRES_PASSWORD: "K_OraouOi1SoJpCKmOzWxZE_RHeuhoFE"
    volumes:
      - todo_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "cT0qZviD_ob9yi2d0_T_85Xeo215IVrY"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_test
      POSTGRES_PASSWORD: "BXuYlaDajq0rZ1fZY3iv20_vtug5bZS4"
    volumes:
      - todo_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "SNr5YFzsMaX-0ELoGqQ0YyaTBTk_Xckg"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  todo_data:
  todo_test_data:
